### ISSUE TITLE
URL Regex rejects valid urls

### ISSUE THREAD

**Issue by rperce** [academo/grafana-alerting-ntfy-webhook-integration#3]
The url regex at time of writing is `(https?://.*?)/(\w+)$`. The last segment is required to be only word characters, which, notably, excludes hyphens and other symbols that are perfectly valid in URLs. In particular, I always generate a UUID for my ntfy topics, which have a dash in them. Swapping out `\w` for `.` would do, or if you really want to be precise, the valid characters for a url path, except for slash, are `[-a-zA-Z0-9()@:%_\+.~#?&=]`.

**Comment by academo** [comment]
Thanks for the tip. https://github.com/academo/grafana-alerting-ntfy-webhook-integration/commit/afc2f26da8991445e39e02981127e576b945f945
